package com.yatrasathi.backend.trainfood.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.Map;

@Service
@Slf4j
public class TrainFoodService {

    private final WebClient webClient;
    private final com.yatrasathi.backend.travel.repository.TravelPlanRepository travelPlanRepository;
    
    // The specific x-auth token generated by v3/pnr/stations/token
    private static final String X_AUTH_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2Mjc1NDY1NCIsInN1YiI6IlJPTEU9Q1VTVE9NRVI7IiwiZXhwIjoxNzg0NzIyNzcyfQ.0WIYt7Ew-SVS6o61AlKakhtx81XBKRqqOXyeIRxFZAI";
    // Actually, looking at the cURL for /pnr/stations/token there's no auth token in the request, it returns one. 
    // Wait, the order curl uses x-auth: eyJhbGciOiJIUzI1NiJ9... for the customer ID 62754654.
    // I will use this hardcoded customer x-auth token for the /order api.
    private static final String ORDER_X_AUTH_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3Y2JiZDZmYy0zYjAyLTRmNTktOGVhMS1mNzZlYzQ3NDNmZWUiLCJzdWIiOiJwbnI9ODkzNzAxODYwMTsiLCJleHAiOjE3ODU5Mjc2NzB9.KRTRR93c4BRjOsEpx7crNKRYFnOEeEhtKgHOeWs1mcA";

    // The token required for the /pnr/stations/token GET request (from user's original cURL)
    private static final String PNR_TOKEN = "0cAFcWeA4dJQ4OuyJo2cClBVknR2twtTRsAmbLGxaoRNMv84O20WaxTkx60CbEeOxGF2YaX7DApU4Jn16pL1zNeoLaAXZLOEKWxK3J32e6NBMEyHHjNabaBms2eNfS2u3AIVtUcBU94GiAij5qlQ-qezaA2gZuz7IiaWgnWh4B5lwc46-7IsnHELXu3xeWyxRstNCXj2VeIFTtYRi7mJXgofnVMwFoGay92zSSsqwJEqNUOxwjZQ7PMxrrpZW4NL-7FU4rFI0eUpPGmPLZx_7hyVCbypzVa8d";

    public TrainFoodService(WebClient.Builder webClientBuilder, com.yatrasathi.backend.travel.repository.TravelPlanRepository travelPlanRepository) {
        this.webClient = webClientBuilder.baseUrl("https://stage-ecatering.ipsator.com").build();
        this.travelPlanRepository = travelPlanRepository;
    }

    public Map<String, Object> getStationsByPnr(String pnr) {
        // GET /api/v3/pnr/stations/token?pnr={pnr}&reverseVendorId=&isReverseOrder=&_=1784718069868
        return webClient.get()
                .uri(uriBuilder -> uriBuilder
                        .path("/api/v3/pnr/stations/token")
                        .queryParam("pnr", pnr)
                        .build())
                .header("app-name", "android_app") // Bypasses Captcha!
                .header("deviceId", "f43ee7f0151e507bd2a9c7b5f173377d")
                .header("token", "dummy_" + System.currentTimeMillis()) // Bypasses Redis replay check
                .retrieve()
                .bodyToMono(Map.class)
                .block(); // Blocking because we're returning Map, not Mono for simplicity
    }

    private String fetchCustomerAuthToken() {
        // Fetch a fresh customer X-AUTH token
        Map<String, String> payload = Map.of(
            "mobile", "7753802853",
            "email", "pareshparimal@gmail.com"
        );
        
        try {
            org.springframework.http.ResponseEntity<Map> responseEntity = webClient.post()
                    .uri("/api/v3/customer")
                    .header("app-name", "desktop web")
                    .header("deviceId", "f43ee7f0151e507bd2a9c7b5f173377d")
                    .header("x-auth", PNR_TOKEN) // PNR token can be passed to get customer token
                    .bodyValue(payload)
                    .retrieve()
                    .toEntity(Map.class)
                    .block();
                    
            if (responseEntity != null && responseEntity.getHeaders().containsKey("X-AUTH")) {
                return responseEntity.getHeaders().getFirst("X-AUTH");
            }
        } catch (Exception e) {
            log.error("Failed to fetch fresh customer X-AUTH token", e);
        }
        return ORDER_X_AUTH_TOKEN; // Fallback to hardcoded if it fails
    }

    public Map<String, Object> placeOrder(Map<String, Object> orderPayload, java.util.UUID planId) {
        String freshCustomerToken = fetchCustomerAuthToken();
        log.info("Using fresh customer token for order: " + freshCustomerToken);
        
        try {
            // Dynamically fix the payload to use a valid outlet and item for the requested station
            Map<String, Object> deliveryDetails = (Map<String, Object>) orderPayload.get("deliveryDetails");
            Map<String, Object> station = (Map<String, Object>) deliveryDetails.get("station");
            String stationCode = (String) station.get("code");
            String coach = (String) deliveryDetails.get("coach");
            Map<String, Object> delivery = (Map<String, Object>) deliveryDetails.get("delivery");
            String fullDate = (String) delivery.get("date"); // e.g. "2026-07-24 20:40 IST"
            String date = fullDate.split(" ")[0];
            String time = fullDate.split(" ")[1];

            // 1. Fetch Outlets for the station
            Map<String, Object> outletsResponse = webClient.get()
                    .uri(uriBuilder -> uriBuilder
                            .path("/api/v3/station/" + stationCode + "/outlets")
                            .queryParam("stationCode", stationCode)
                            .queryParam("time", time)
                            .queryParam("date", date)
                            .queryParam("coach", coach)
                            .build())
                    .header("app-name", "desktop web")
                    .header("deviceId", "f43ee7f0151e507bd2a9c7b5f173377d")
                    .header("x-auth", freshCustomerToken) // FIXED: Use fresh JWT instead of captcha string!
                    .retrieve()
                    .bodyToMono(Map.class)
                    .block();

            if (outletsResponse != null && "success".equals(outletsResponse.get("status"))) {
                Map<String, Object> result = (Map<String, Object>) outletsResponse.get("result");
                java.util.List<Map<String, Object>> outletsList = (java.util.List<Map<String, Object>>) result.get("outlets");
                
                if (outletsList != null && !outletsList.isEmpty()) {
                    Map<String, Object> outerVendor = outletsList.get(0);
                    Integer vendorId = (Integer) outerVendor.get("id");
                    java.util.List<Map<String, Object>> innerOutlets = (java.util.List<Map<String, Object>>) outerVendor.get("outlets");
                    Integer outletId = (Integer) innerOutlets.get(0).get("id");

                    // 2. Fetch Menu for the vendor/outlet
                    Map<String, Object> menuResponse = webClient.get()
                            .uri("/api/v2/vendor/" + vendorId + "/outlet/" + outletId + "/menu/active")
                            .header("app-name", "android_app")
                            .retrieve()
                            .bodyToMono(Map.class)
                            .block();

                    if (menuResponse != null && "success".equals(menuResponse.get("status"))) {
                        Map<String, Object> menuResult = (Map<String, Object>) menuResponse.get("result");
                        java.util.List<Map<String, Object>> categories = (java.util.List<Map<String, Object>>) menuResult.get("categories");
                        if (categories != null && !categories.isEmpty()) {
                            java.util.List<Map<String, Object>> items = (java.util.List<Map<String, Object>>) categories.get(0).get("items");
                            if (items != null && !items.isEmpty()) {
                                String itemId = String.valueOf(items.get(0).get("id"));
                                
                                // 3. Update the payload
                                orderPayload.put("outlet", Map.of("id", outletId, "vendor", Map.of("id", vendorId)));
                                java.util.List<Map<String, Object>> orderItems = (java.util.List<Map<String, Object>>) orderPayload.get("orderItems");
                                orderItems.get(0).put("id", itemId);
                                orderItems.get(0).put("itemId", itemId);
                                log.info("Dynamically updated payload for station {}: Vendor {}, Outlet {}, Item {}", stationCode, vendorId, outletId, itemId);
                            } else {
                                return Map.of("status", "failure", "message", "No menu items available at " + stationCode + " right now.");
                            }
                        } else {
                            return Map.of("status", "failure", "message", "No menu categories available at " + stationCode + " right now.");
                        }
                    } else {
                        return Map.of("status", "failure", "message", "Failed to fetch menu for " + stationCode);
                    }
                } else {
                    return Map.of("status", "failure", "message", "No restaurants available at " + stationCode + " right now on the staging server.");
                }
            } else {
                return Map.of("status", "failure", "message", "Failed to fetch outlets for " + stationCode);
            }
        } catch (Exception e) {
            log.error("Failed to dynamically fix order payload", e);
            return Map.of("status", "failure", "message", "Internal Error while fetching dynamic outlets: " + e.getMessage());
        }

        try {
            Map<String, Object> response = webClient.post()
                    .uri("/api/v3/order")
                    .header("app-name", "desktop web")
                    .header("deviceId", "f43ee7f0151e507bd2a9c7b5f173377d")
                    .header("x-auth", freshCustomerToken)
                    .bodyValue(orderPayload)
                    .retrieve()
                    .bodyToMono(Map.class)
                    .block();

            if (response != null && planId != null) {
                try {
                    if ("success".equals(response.get("status"))) {
                        Map<String, Object> result = (Map<String, Object>) response.get("result");
                        if (result != null && result.get("id") != null) {
                            String orderId = String.valueOf(result.get("id"));
                            travelPlanRepository.findById(planId).ifPresent(plan -> {
                                plan.setEcateringOrderId(orderId);
                                travelPlanRepository.save(plan);
                            });
                        }
                    }
                } catch (Exception e) {
                    log.error("Failed to save ecateringOrderId to TravelPlan", e);
                }
            }
            return response;
        } catch (org.springframework.web.reactive.function.client.WebClientResponseException e) {
            log.error("Order API Failed with status {}: {}", e.getStatusCode(), e.getResponseBodyAsString());
            try {
                // Return the actual error response from staging instead of 500
                com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
                return mapper.readValue(e.getResponseBodyAsString(), Map.class);
            } catch (Exception ex) {
                return Map.of("status", "error", "message", e.getResponseBodyAsString());
            }
        }
    }
}
